os10_system:
  hostname: pd99-elf-001
os10_bgp:
  asn: 4210199001
  best_path:
    as_path: multipath-relax
  graceful_restart: true
  maxpath_ebgp: 2
  bfd_all_neighbors:
    interval: 100
    min_rx: 100
    multiplier: 3
    role: active
    state: present
  neighbor:
  - adv_interval: 1
    fall_over: present
    name: spine-leaf
    timer: 3 9
    type: peergroup
    send_community:
      - type: standard
        state: present
    address_family:
    - allow_as_in: 1
      type: ipv4
      route_map:
        - name: spine-leaf
          filter: out
          state: present
  - ip: 169.254.35.0
    admin: up  
    description: pd99-esp-001
    peergroup: spine-leaf
    remote_asn: 4210199000
    type: ipv4
  - ip: 169.254.45.0
    admin: up
    description: pd99-esp-002
    peergroup: spine-leaf
    remote_asn: 4210199000
    type: ipv4
  - ip: 169.254.56.1
    admin: up
    description: pd99-elf-002
    remote_asn: 4210199001
    type: ipv4
    adv_interval: 1
    fall_over: present
    timer: 3 9
    address_family:
    - type: ipv4
      route_map:
        - name: spine-leaf
          filter: out
          state: present
  redistribute:
  - address_type: ipv4
    route_type: connected
  router_id: 10.99.0.5
os10_interface:
  ethernet 1/1/53:
    admin: up
    desc: to pd99-esp-001 e1/1/20
    ip_and_mask: 169.254.35.1/31
    mtu: 9216
    switchport: false
  ethernet 1/1/54:
    admin: up
    desc: to pd99-esp-002 e1/1/21
    ip_and_mask: 169.254.45.1/31
    mtu: 9216
    switchport: false
  ethernet 1/1/55:
    admin: up
    desc: VLT to pd99-elf-002 1/1/55
    mtu: 9216
    switchport: false
  ethernet 1/1/56:
    admin: up
    desc: VLT to pd99-elf-002 1/1/56
    mtu: 9216
    switchport: false
  ethernet 1/1/49:
    admin: up
    desc: to pd99-eag-001 1/1/25
    mtu: 9216
    switchport: false
  ethernet 1/1/51:
    admin: up
    desc: to pd99-eag-002 1/1/26
    mtu: 9216
    switchport: false
  ethernet 1/1/1:1:
    admin: up
    desc: to compute server 2
    mtu: 9216
#    portmode: trunk
    switchport: true
  ethernet 1/1/2:1:
    admin: up
    desc: to bridge server
    mtu: 9216
#    portmode: trunk
    switchport: true
  Po 1:
    admin: up
    desc: to pd99-eag-001 and pd99-eag-002
    mtu: 9216
    portmode: trunk
    switchport: true
  loopback 0:
    admin: up
    ip_and_mask: 10.99.0.5/32
os10_lag:
  Po 1:
    type: dynamic
    channel_members:
      - port: ethernet 1/1/49
        mode: active
      - port: ethernet 1/1/51
        mode: active
    state: present
os10_lldp:
  enable: true
os10_bfd:
  bfd:
    state: present
os10_prefix_list:
- name: spine-leaf
  state: present
  type: ipv4
  entries:
  - condition_list:
    - condition: ge
      prelen: '24'
    mask: '16'
    net_num: 10.99.0.0
    number: 10
    permit: true
    state: present
  - condition_list:
    - condition: ge
      prelen: '24'
    mask: '16'
    net_num: 169.254.0.0
    number: 20
    permit: true
    state: present
  - condition_list:
    - condition: ge
      prelen: '24'
    mask: '16'
    net_num: 172.10.0.0
    number: 30
    permit: true
    state: present
- name: v3133
  state: present
  type: ipv4
  entries:
  - condition_list:
    - condition: ge
      prelen: '24'
    - condition: le
      prelen: '24'
    mask: '16'
    net_num: 172.20.0.0
    number: 10
    permit: true
    state: present
os10_route_map:
  route_map:
  - name: spine-leaf
    permit: true
    seq_num: 10
    match:
    - ip_type: ipv4
      prefix_list: spine-leaf
    set:
      community: "65000:0"
  - name: spine-leaf
    permit: true
    seq_num: 20
    match:
    - ip_type: ipv4
      prefix_list: v3133
    set:
      community: "65000:9"
os10_vlan:
  Vlan 20:
    description: compute server 2
    ip_and_mask: 172.10.20.253/24
    state: present
    untagged_members:
    - port: ethernet 1/1/1:1
      state: present
  Vlan 30:
    description: baremetal server
    ip_and_mask: 172.10.30.253/24
    state: present
    tagged_members:
    - port: Po 1
      state: present
  Vlan 4000:
    description: to pd99-elf-002 VLAN4000
    ip_and_mask: 169.254.56.0/31
    state: present

os10_vrrp:
  vlan 20:
    vrrp_group:
      - group_id: 1
        virtual_address:
          - ip: 172.10.20.1
            state: present
        priority: 200
        state: present
  vlan 30:
    vrrp_group:
      - group_id: 1
        virtual_address:
          - ip: 172.10.30.1
            state: present
        priority: 200
        state: present

os10_vlt:
  backup_destination: 10.204.10.16
  destination_type: ipv4
  discovery_intf: 1/1/55-1/1/56
  discovery_intf_state: present
  domain: 127
  peer_routing: true
  vlt_mac: 00:00:00:00:00:02
  vlt_peers:
    Po 1:
      peer_lag: 1

os10_xstp:
  enable: true
  intf:
    ethernet 1/1/1:1:
      edge_port: true
    ethernet 1/1/2:1:
      edge_port: true
  rstp:
    bridge_priority: 0
  type: rstp

os10_ntp:
  server:
    - ip: 143.166.255.32
      prefer: true
      state: present